# -*- coding: utf-8 -*-
"""YOLOv8CustomObjectDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RExi6QKodKbe8PclYPyqOAqsEKWC5fr7
"""

!pip install ultralytics

from ultralytics import YOLO
import os
from IPython.display import display, Image
from IPython import display
display.clear_output()

!yolo checks

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="wKPgK90xGcfBdWp6f8tt")
project = rf.workspace("workspace-il5zj").project("object-detection-plm7l")
version = project.version(1)
dataset = version.download("yolov8")

!yolo task=detect mode=train model=yolov8m.pt data={dataset.location}/data.yaml epochs=100 imgsz=640

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt source=/content/key_2.jpg

!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt source=/content/souris-usb-havit-ms753-tunisie.jpg

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg'):
  display(Image(filename=image_path, height=600))
  print("\n")